config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products
   root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.where(user_id: current_user.id)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user = current_user
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:ItemId, :cost, :Purpose, :Out_of_stock)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
 <head>
<title>SHOPKEEPERS APP</title>  <%= csrf_meta_tags %>
<style>
nav{
float: left;
height: 575px;
background-color: #9C27B0;
padding-right: 20px;
border: 30px;
margin-right: 20px;
 }
 .btn{
 color: white;
 text-decoration: none;
 }
 .container2{
  border: 20px;
  margin-left: 40px;
  }
 #logo{
 font-size:400%;
 text-decoration: none;
 background-color: #9C27B0;

  float: top;
  }
  table, th, td {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;

   }
    td, th{
      border: 1px solid #ddd;
   padding: 16px; }
   tr:nth-child(even){background-color: #f2f2f2;}
   tr:hover {background-color: #ddd;}
   th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #9C27B0;
  color: white;
 }
  body{
 background-color: rgb(0,0,50);
   }
 .heading{
  background-color: #9C27B0;
  height: 70px;
  padding-top: 20px;
  color: white;
  }
}
</style>
  <%= stylesheet_link_tag    'application', media: 'all',
                             'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
<header class="navbar navbar-fixed-top navbar-inverse">
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  <div class="container">
    <center class="heading"><h1>
    Shopkeepers Inventory</h1>
    </center>
    <nav>
      <ul class="nav navbar-nav navbar-right"><h3>
        <li><%= link_to "Home",   products_path , class: "btn" %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Account", edit_user_registration_path, class: "btn "  %></li>
          <li>
            <%= link_to('Logout', destroy_user_session_path, method: :delete)=%>
          </li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_registration_path, class: "btn " %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "btn " %></li>
        <% end %></h3>
      </ul>
    </nav>
  </div>
</header>
<div class="container2">

  <%= yield %>
</div></body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ItemId %>
    <%= form.number_field :ItemId %>
  </div>

  <div class="field">
    <%= form.label :cost %>
    <%= form.number_field :cost %>
  </div>

  <div class="field">
    <%= form.label :Purpose %>
    <%= form.text_field :Purpose %>
  </div>
  <div class="field">
    <%= form.label :Out_of_stock %>
    <%= form.check_box :Out_of_stock %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>ItemId</th>
      <th>Cost</th>
      <th>Purpose</th>
      <th>Out of Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.ItemId %></td>
        <td><%= product.cost %></td>
        <td><%= product.Purpose %></td>
        <td><%= product.Out_of_stock %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<u>
<%= link_to 'New Product', new_product_path %>
</u>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ItemId:</strong>
  <%= @product.ItemId %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @product.cost %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @product.Purpose %>
</p>
<p>
  <strong>Out_of_stock:</strong>
  <%= @product.Out_of_stock %>
</p>
<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>